const mongoose = require("mongoose");

const userSettingsSchema = new mongoose.Schema(
  {
    userId: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true, unique: true },
    language: {
      code: { type: String, default: "en" },
      name: { type: String, default: "English" },
      nativeName: { type: String, default: "English" },
      autoDetect: { type: Boolean, default: true },
      translateDynamic: { type: Boolean, default: true },
      translateChat: { type: Boolean, default: false },
    },
    theme: {
      mode: { type: String, enum: ["light", "dark", "system"], default: "system" },
      fontSize: { type: String, enum: ["small", "medium", "large"], default: "medium" },
      layout: { type: String, enum: ["compact", "comfortable"], default: "comfortable" },
      highContrast: { type: Boolean, default: false },
      animationIntensity: { type: String, enum: ["low", "medium", "high"], default: "medium" },
      bannerAutoplay: { type: Boolean, default: true },
    },
    notifications: {
      orderUpdates: { type: Boolean, default: true },
      promotions: { type: Boolean, default: true },
      discounts: { type: Boolean, default: true },
      newProducts: { type: Boolean, default: true },
      deliveryUpdates: { type: Boolean, default: true },
      aiRecommendations: { type: Boolean, default: true },
      chatMessages: { type: Boolean, default: true },
      supportMessages: { type: Boolean, default: true },
      securityAlerts: { type: Boolean, default: true },
      accountActivity: { type: Boolean, default: true },
      sound: { type: String, default: "default" },
      vibration: { type: Boolean, default: true },
      previews: { type: Boolean, default: true },
      quietHoursEnabled: { type: Boolean, default: false },
      quietHoursStart: { type: String, default: "22:00" },
      quietHoursEnd: { type: String, default: "07:00" },
    },
    ai: {
      cookingAssistant: { type: Boolean, default: true },
      smartSearch: { type: Boolean, default: true },
      recommendations: { type: Boolean, default: true },
      ingredientSubstitutes: { type: Boolean, default: true },
      budgetPlanner: { type: Boolean, default: true },
      weeklyPlanner: { type: Boolean, default: true },
      nutritionAdvisor: { type: Boolean, default: true },
      voiceAssistant: { type: Boolean, default: false },
      shoppingChatbot: { type: Boolean, default: true },
      useOrderHistory: { type: Boolean, default: true },
      useFavorites: { type: Boolean, default: true },
      useBrowsing: { type: Boolean, default: true },
      useSearchHistory: { type: Boolean, default: true },
      responseLanguage: { type: String, default: "english" },
      responseLength: { type: String, enum: ["short", "medium", "long"], default: "medium" },
      voiceResponses: { type: Boolean, default: false },
    },
    privacy: {
      dataSharing: { type: Boolean, default: false },
      analytics: { type: Boolean, default: true },
      cookieConsent: { type: Boolean, default: false },
    },
    security: {
      biometricAuth: { type: Boolean, default: false },
      twoFactorAuth: { type: Boolean, default: false },
      sessionTimeout: { type: Number, default: 30 },
      trustedDevices: { type: [String], default: [] },
    },
    delivery: {
      defaultAddress: { type: String, default: "" },
      preferredTimeWindow: { type: String, default: "" },
      defaultPaymentMethod: { type: String, default: "" },
      deliveryInstructions: { type: String, default: "" },
      receiptPreference: { type: String, enum: ["email", "sms", "none"], default: "email" },
      orderHistoryRetention: { type: Number, default: 365 },
      autoReorder: { type: Boolean, default: false },
      liveTracking: { type: Boolean, default: true },
      autoOpenTracking: { type: Boolean, default: false },
    },
    accessibility: {
      voiceCommands: { type: Boolean, default: false },
      speechResponses: { type: Boolean, default: false },
      speechRecognitionLanguage: { type: String, default: "en-US" },
      fontScaling: { type: Number, default: 1.0 },
      screenReader: { type: Boolean, default: false },
      hapticFeedback: { type: Boolean, default: true },
      buttonSize: { type: String, enum: ["small", "normal", "large"], default: "normal" },
      colorAccessibility: { type: Boolean, default: false },
      simplifiedNavigation: { type: Boolean, default: false },
    },
    storage: {
      cacheImages: { type: Boolean, default: true },
      wifiOnlyImages: { type: Boolean, default: false },
      autoplayVideos: { type: Boolean, default: true },
      cacheTranslations: { type: Boolean, default: true },
    },
  },
  { timestamps: true }
);

module.exports = mongoose.model("UserSettings", userSettingsSchema);
